{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/healthDataErrorError(error:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"healthDataErrorError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/digimecore\/sdkerror\/healthdataerrorerror(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"type":"text","text":"Authorization failed with the specified error"}],"metadata":{"title":"SDKError.healthDataErrorError(error:)","role":"symbol","externalID":"s:10DigiMeCore8SDKErrorO015healthDataErrorG0yACs0G0_p_tcACmF","modules":[{"name":"DigiMeCore"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"healthDataErrorError","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"references":{"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SDKError":{"type":"topic","abstract":[{"text":"SDK Errors","type":"text"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError","kind":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"title":"SDKError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"url":"\/documentation\/digimecore\/sdkerror"},"doc://DigiMeCore/documentation/DigiMeCore/SDKError/healthDataErrorError(error:)":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"healthDataErrorError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"title":"SDKError.healthDataErrorError(error:)","type":"topic","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/healthDataErrorError(error:)","abstract":[{"type":"text","text":"Authorization failed with the specified error"}],"kind":"symbol","url":"\/documentation\/digimecore\/sdkerror\/healthdataerrorerror(error:)","role":"symbol"}}}