{"identifier":{"url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"SDKError.urlRequestFailed(error:)","roleHeading":"Case","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","symbolKind":"case","role":"symbol","modules":[{"name":"DigiMeCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DigiMeCore/documentation/DigiMeCore/SDKError":{"type":"topic","abstract":[{"text":"SDK Errors","type":"text"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError","kind":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"title":"SDKError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"url":"\/documentation\/digimecore\/sdkerror"},"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","abstract":[{"type":"text","text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError"}],"kind":"symbol","url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"type":"topic","title":"SDKError.urlRequestFailed(error:)"}}}