{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"DigiMeCore"}],"title":"SDKError.urlRequestFailed(error:)","roleHeading":"Case","symbolKind":"case","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlRequestFailed"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"variants":[{"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","interfaceLanguage":"swift"},"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/digimecore"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"role":"symbol","url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"title":"SDKError.urlRequestFailed(error:)","abstract":[{"type":"text","text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError"}],"type":"topic"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError":{"title":"SDKError","type":"topic","abstract":[{"type":"text","text":"SDK Errors"}],"role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDKError","kind":"identifier"}],"url":"\/documentation\/digimecore\/sdkerror","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"kind":"symbol"}}}