{"kind":"symbol","metadata":{"title":"error","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DigiMeCore"}],"externalID":"s:10DigiMeCore9SyncErrorV5errorAA07ServiceE0VSgvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","kind":"typeIdentifier","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/ServiceError","text":"ServiceError"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/error"]}],"identifier":{"url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SyncError":{"abstract":[{"type":"text","text":"Reason why connecting to source or importing data from source into userâ€™s library failed"}],"kind":"symbol","url":"\/documentation\/digimecore\/syncerror","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError","title":"SyncError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SyncError"}]},"doc://DigiMeCore/documentation/DigiMeCore/SyncError/error":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"text":"ServiceError","kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","url":"\/documentation\/digimecore\/syncerror\/error","role":"symbol","abstract":[],"title":"error"},"doc://DigiMeCore/documentation/DigiMeCore/ServiceError":{"abstract":[],"role":"symbol","title":"ServiceError","navigatorTitle":[{"text":"ServiceError","kind":"identifier"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/ServiceError","url":"\/documentation\/digimecore\/serviceerror","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ServiceError","kind":"identifier"}],"kind":"symbol"}}}