{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror"]}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/Se","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/SQ"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/statusCode"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/Equatable-Implementations"]}],"abstract":[{"type":"text","text":"Reason why connecting to source or importing data from source into user’s library failed"}],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore"]]},"metadata":{"modules":[{"name":"DigiMeCore"}],"navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"roleHeading":"Structure","symbolKind":"struct","role":"symbol","externalID":"s:10DigiMeCore9SyncErrorV","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SyncError"}],"title":"SyncError"},"identifier":{"url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError","interfaceLanguage":"swift"},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/code":{"title":"code","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/code","kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/error":{"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/error","kind":"symbol","title":"error"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/equatable-implementations","kind":"article","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/Equatable-Implementations"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/statusCode":{"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/statusCode","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/statuscode","kind":"symbol","title":"statusCode"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/init(from:)":{"url":"\/documentation\/digimecore\/syncerror\/init(from:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"init(from:)","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/init(from:)"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","url":"\/documentation\/digimecore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","title":"SyncError","role":"symbol","url":"\/documentation\/digimecore\/syncerror","abstract":[{"text":"Reason why connecting to source or importing data from source into user’s library failed","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SyncError","kind":"identifier"}],"navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/Se"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/SQ":{"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/SQ","title":"Swift.Equatable","type":"unresolvable"}}}