{"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Case","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","title":"SDKError.urlRequestFailed(error:)","symbolKind":"case","modules":[{"name":"DigiMeCore"}]},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError":{"navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"SDK Errors"}],"title":"SDKError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDKError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError","url":"\/documentation\/digimecore\/sdkerror"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","title":"DigiMeCore","role":"collection","kind":"symbol"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","role":"symbol","type":"topic","title":"SDKError.urlRequestFailed(error:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}]}}}