{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/code"]}],"metadata":{"role":"symbol","modules":[{"name":"DigiMeCore"}],"externalID":"s:10DigiMeCore9SyncErrorV4codeSSvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"code","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/code":{"url":"\/documentation\/digimecore\/syncerror\/code","role":"symbol","title":"code","abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"role":"symbol","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"type":"topic","url":"\/documentation\/digimecore\/syncerror","navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"title":"SyncError","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/digimecore"}}}