{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/error"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:10DigiMeCore9SyncErrorV5errorAA07ServiceE0VSgvp","symbolKind":"property","title":"error","roleHeading":"Instance Property","modules":[{"name":"DigiMeCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","text":"ServiceError"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/digimecore"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/error":{"url":"\/documentation\/digimecore\/syncerror\/error","role":"symbol","title":"error","abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV"},{"text":"?","kind":"text"}]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/ServiceError":{"url":"\/documentation\/digimecore\/serviceerror","title":"ServiceError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ServiceError","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","navigatorTitle":[{"kind":"identifier","text":"ServiceError"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"role":"symbol","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"type":"topic","url":"\/documentation\/digimecore\/syncerror","navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"title":"SyncError","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"}}}