{"metadata":{"title":"error","roleHeading":"Instance Property","externalID":"s:10DigiMeCore9SyncErrorV5errorAA07ServiceE0VSgvp","symbolKind":"property","modules":[{"name":"DigiMeCore"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","text":"ServiceError"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error"},"kind":"symbol","variants":[{"paths":["\/documentation\/digimecore\/syncerror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","text":"ServiceError","preciseIdentifier":"s:10DigiMeCore12ServiceErrorV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/ServiceError":{"abstract":[],"role":"symbol","type":"topic","title":"ServiceError","navigatorTitle":[{"text":"ServiceError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ServiceError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/ServiceError","url":"\/documentation\/digimecore\/serviceerror"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"url":"\/documentation\/digimecore\/syncerror","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"role":"symbol","type":"topic","title":"SyncError","kind":"symbol","navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SyncError","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/error":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/error","url":"\/documentation\/digimecore\/syncerror\/error","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10DigiMeCore12ServiceErrorV","kind":"typeIdentifier","text":"ServiceError"},{"kind":"text","text":"?"}],"type":"topic","title":"error"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","title":"DigiMeCore","role":"collection","kind":"symbol"}}}